/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uff.ic.archd.db.dao;

/**
 *
 * @author wallace
 */
public class Constants {
    public final static String DB_DIR = System.getProperty("user.home") + "/.archDB11/METRIC_VALUE_DB_DIR/";
    //archDB10 MapDB
    //archDB11 titan
//    /archDB12 guava
    //archDB13 orientdb
    //archDB14 Neo4j
    //storm
    //log4j
    
    public final static int ANOMALIE_GOD_PACKAGE = 1;
    public final static int ANOMALIE_GOD_CLASS = 2;
    public final static int ANOMALIE_MISPLACED_CLASS = 3;
    public final static int ANOMALIE_FEATURE_ENVY = 4;
    public final static int ANOMALIE_SHOTGUN_SURGERY = 5;
    public final static int ANOMALIE_GOD_METHOD = 6;
    
    public final static int ANOMALIE_TYPE_CONGENITAL_NEVER_CORRECTED_BORN_WITH_THE_CLASS = 1;
    public final static int ANOMALIE_TYPE_CONGENITAL_NOT_CORRECTED_BUT_CORRECTED_ONE_TIME_BORN_WITH_THE_CLASS = 2;
    public final static int ANOMALIE_TYPE_CONGENITAL_NOT_CORRECTED_RECURRENT_CORRECTED_BORN_WITH_THE_CLASS = 3;
    public final static int ANOMALIE_TYPE_CONGENITAL_CORRECTED_BORN_WITH_THE_CLASS = 4;
    public final static int ANOMALIE_TYPE_CONGENITAL_CORRECTED_BUT_CORRECTED_UM_TIME_BEFORE_BORN_WITH_THE_CLASS = 5;
    public final static int ANOMALIE_TYPE_CONGENITAL_CORRECTED_RECURRENT_CORRECTED_BORN_WITH_THE_CLASS = 6;
    public final static int ANOMALIE_TYPE_ADQUIRED_NEVER_CORRECTED_BORN_WITH_THE_CLASS = 7;
    public final static int ANOMALIE_TYPE_ADQUIRED_NOT_CORRECTED_BUT_CORRECTED_ONE_TIME_BORN_WITH_THE_CLASS = 8;
    public final static int ANOMALIE_TYPE_ADQUIRED_NOT_CORRECTED_RECURRENT_CORRECTED_BORN_WITH_THE_CLASS = 9;
    public final static int ANOMALIE_TYPE_ADQUIRED_CORRECTED_BORN_WITH_THE_CLASS = 10;
    public final static int ANOMALIE_TYPE_ADQUIRED_CORRECTED_BUT_CORRECTED_UM_TIME_BEFORE_BORN_WITH_THE_CLASS = 11;
    public final static int ANOMALIE_TYPE_ADQUIRED_CORRECTED_RECURRENT_CORRECTED_BORN_WITH_THE_CLASS = 12;
    public final static int ANOMALIE_TYPE_CONGENITAL_NEVER_CORRECTED_BORN_AFTER_THE_CLASS = 13;
    public final static int ANOMALIE_TYPE_CONGENITAL_NOT_CORRECTED_BUT_CORRECTED_ONE_TIME_BORN_AFTER_THE_CLASS = 14;
    public final static int ANOMALIE_TYPE_CONGENITAL_NOT_CORRECTED_RECURRENT_CORRECTED_BORN_AFTER_THE_CLASS = 15;
    public final static int ANOMALIE_TYPE_CONGENITAL_CORRECTED_BORN_AFTER_THE_CLASS = 16;
    public final static int ANOMALIE_TYPE_CONGENITAL_CORRECTED_BUT_CORRECTED_UM_TIME_BEFORE_BORN_AFTER_THE_CLASS = 17;
    public final static int ANOMALIE_TYPE_CONGENITAL_CORRECTED_RECURRENT_CORRECTED_BORN_AFTER_THE_CLASS = 18;
    public final static int ANOMALIE_TYPE_ADQUIRED_NEVER_CORRECTED_BORN_AFTER_THE_CLASS = 19;
    public final static int ANOMALIE_TYPE_ADQUIRED_NOT_CORRECTED_BUT_CORRECTED_ONE_TIME_BORN_AFTER_THE_CLASS = 20;
    public final static int ANOMALIE_TYPE_ADQUIRED_NOT_CORRECTED_RECURRENT_CORRECTED_BORN_AFTER_THE_CLASS = 21;
    public final static int ANOMALIE_TYPE_ADQUIRED_CORRECTED_BORN_AFTER_THE_CLASS = 22;
    public final static int ANOMALIE_TYPE_ADQUIRED_CORRECTED_BUT_CORRECTED_UM_TIME_BEFORE_BORN_AFTER_THE_CLASS = 23;
    public final static int ANOMALIE_TYPE_ADQUIRED_CORRECTED_RECURRENT_CORRECTED_BORN_AFTER_THE_CLASS = 24;
}
