/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uff.ic.archd.db.dao;

import br.uff.ic.archd.javacode.JavaInterface;
import br.uff.ic.archd.javacode.JavaPackage;
import br.uff.ic.archd.javacode.JavaProject;
import java.io.File;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author wallace
 */
public class HsqldbInterfaceDao implements InterfaceDao{

    private Connection connection;
    
    HsqldbInterfaceDao(){
        try {
            File file = new File(Constants.DB_DIR);
            if(!file.exists()){
                file.mkdirs();
                
            }
            Class.forName("org.hsqldb.jdbcDriver");
            connection = DriverManager.getConnection("jdbc:hsqldb:file:" + Constants.DB_DIR, "archd", "123");
            DatabaseMetaData dbData = connection.getMetaData();
            ResultSet tables = dbData.getTables(null, null, "JAVA_INTERFACES", null);
            //System.out.println("NEXT "+tables.next());
            if (!tables.next()) {


                System.out.println("NAO POSSUI TABELA JAVA_INTERFACES");
                Statement stm = connection.createStatement();

                stm.executeUpdate("create table JAVA_INTERFACES (id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), "
                        + "name varchar(1000),"
                        + "path varchar(1000),"
                        + "revision_id varchar(1000),"
                        + "PRIMARY KEY (id));");
            } else {
                System.out.println("TABELA JAH EXISTE JAVA_INTERFACES");
            }

            //stm.execute("SHUTDOWN");

        } catch (ClassNotFoundException e) {
            System.out.println("Erro ao carregar o driver JDBC. ");
        } catch (SQLException e) {
            System.out.println("Erro de SQL: " + e);
            //e.printStackTrace();
        } catch (Exception e) {
            System.out.println("ERRO interface " + e.getMessage());
        }

    }
    @Override
    public void save(JavaInterface javaInterface) {
        try {
            Statement stm = connection.createStatement();
            System.out.println("insert into JAVA_INTERFACES (name ,"
                    + "path,"
                    + "revision_id ,"
                    + "java_package ) "
                    + " VALUES ('" + javaInterface.getFullQualifiedName() + "',"
                    + "'" + javaInterface.getPath() + "',"
                    + "'" + javaInterface.getRevisionId() + "');");
            stm.executeUpdate("insert into JAVA_INTERFACES (name ,"
                    + "path ,"
                    + "revision_id )"
                    + " VALUES ('" + javaInterface.getFullQualifiedName() + "',"
                    + "'" + javaInterface.getPath() + "',"
                    + "'" + javaInterface.getRevisionId() + "');");
            ResultSet rs = stm.executeQuery("CALL IDENTITY();");
            long id = 0;
            if (rs.next()) {
                id = rs.getLong(1);
            }
            javaInterface.setId(id);
            System.out.println("Interface ID: "+javaInterface.getId());
        } catch (SQLException e) {
            System.out.println("ERRO interface: " + e.getMessage());
        }
    }

    @Override
    public List<JavaInterface> getJavaInterfacesByRevisionId(JavaProject javaProject, String revisionId) {
        List<JavaInterface> javaInterfaces = new LinkedList();
        try {
            Statement stm = connection.createStatement();
            
            //long t1 = System.currentTimeMillis();
            ResultSet rs = stm.executeQuery("select * from JAVA_INTERFACES where revision_id='" + revisionId + "';");
            //long t2 = System.currentTimeMillis();
            //System.out.println("Pegar todas as interfaces de uma revisão (somente o select) : "+(t2-t1)+"  milisegundos");
            int i = 0;

            while (rs.next()) {
                
                String path = rs.getString("path");
                String classString = rs.getString("name");
                String classSplit[] = classString.split("\\.");
                String className = classSplit[classSplit.length - 1];
                int n = classString.length() - (className.length()+1);
                if(n < 0){
                    n = 0;
                }
                String classPackage = classString.substring(0, n);
                JavaInterface javaInterface = (JavaInterface) javaProject.getClassByName(classString);
                if (javaInterface == null) {
                    javaInterface = new JavaInterface(path);

                    javaInterface.setName(className);
                    JavaPackage javaPackage = javaProject.getPackageByName(classPackage);
                    if (javaPackage == null) {
                        javaPackage = new JavaPackage(classPackage);
                        javaProject.addPackage(javaPackage);
                    }
                    javaInterface.setJavaPackage(javaPackage);
                    javaPackage.addJavaAbstract(javaInterface);
                }
                javaInterface.setRevisionId(revisionId);
                javaInterface.setId(Long.valueOf(rs.getString("id")));
                javaInterfaces.add(javaInterface);
                javaProject.addClass(javaInterface);
                i++;
            }
            //stm.execute("SHUTDOWN");
            //System.out.println("QUANTIDADE: " + i);
        } catch (Exception e) {
            System.out.println("ERRO get interfaces: " + e.getMessage());
        }
        return javaInterfaces;
    }
    
}
