/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uff.ic.archd.db.dao;

import br.uff.ic.archd.javacode.Parameter;
import java.io.File;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

/**
 *
 * @author wallace
 */
public class HsqldbJavaParameterDao implements JavaParameterDao{

    private Connection connection;
    
    HsqldbJavaParameterDao(){
        try {
            File file = new File(Constants.DB_DIR);
            if(!file.exists()){
                file.mkdirs();
                
            }
            Class.forName("org.hsqldb.jdbcDriver");
            connection = DriverManager.getConnection("jdbc:hsqldb:file:" + Constants.DB_DIR, "archd", "123");
            DatabaseMetaData dbData = connection.getMetaData();
            ResultSet tables = dbData.getTables(null, null, "JAVA_PARAMETERS", null);
            //System.out.println("NEXT "+tables.next());
            if (!tables.next()) {


                System.out.println("NAO POSSUI TABELA JAVA_PARAMETERS");
                Statement stm = connection.createStatement();

                stm.executeUpdate("create table JAVA_PARAMETERS (id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), "
                        + "method_id long,"
                        + "position int,"
                        + "java_data_type varchar(1000),"
                        + "name varchar(1000),"
                        + "PRIMARY KEY (id),"
                        + "FOREIGN KEY (method_id) REFERENCES JAVA_METHODS(id));");
            } else {
                System.out.println("TABELA JAH EXISTE JAVA_PARAMETERS");
            }

            //stm.execute("SHUTDOWN");

        } catch (ClassNotFoundException e) {
            System.out.println("Erro ao carregar o driver JDBC. ");
        } catch (SQLException e) {
            System.out.println("Erro de SQL: " + e);
            //e.printStackTrace();
        } catch (Exception e) {
            System.out.println("ERRO " + e.getMessage());
        }
    }
    
    @Override
    public void save(Parameter parameter) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public List<Parameter> getAllParameterByMethodId(long methodId) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
    
}
