/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uff.ic.archd.db.dao;

import java.io.File;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedList;
import java.util.List;

/**
 *
 * @author wallace
 */
public class HsqldbOriginalNameDao implements OriginalNameDao{
    
    
    private Connection connection;

    public HsqldbOriginalNameDao() {
        try {
            File file = new File(Constants.DB_DIR);
            if (!file.exists()) {
                file.mkdirs();

            }
            Class.forName("org.hsqldb.jdbcDriver");
            connection = DriverManager.getConnection("jdbc:hsqldb:file:" + Constants.DB_DIR, "archd", "123");
            DatabaseMetaData dbData = connection.getMetaData();
            ResultSet tables = dbData.getTables(null, null, "ORIGINAL_NAME", null);
            //System.out.println("NEXT "+tables.next());
            if (!tables.next()) {


                System.out.println("NAO POSSUI TABELA ORIGINAL_NAME");
                Statement stm = connection.createStatement();

                stm.executeUpdate("create table ORIGINAL_NAME (id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), "
                        + "artifact_signature varchar(1000),"
                        + "original_name varchar(1000),"
                        + "PRIMARY KEY (id));");
            } else {
                System.out.println("TABELA JAH EXISTE ORIGINAL_NAME");
            }

            //stm.execute("SHUTDOWN");

        } catch (ClassNotFoundException e) {
            System.out.println("Erro ao carregar o driver JDBC. " + e.getMessage());
        } catch (SQLException e) {
            System.out.println("Erro de SQL: " + e.getMessage());
            //e.printStackTrace();
        } catch (Exception e) {
            System.out.println("ERRO " + e.getMessage());
        }


    }

    @Override
    public void save(String artifactName, String originalName) {
        try {
            Statement stm = connection.createStatement();
            System.out.println("insert into ORIGINAL_NAME (artifact_signature ,"
                    + "original_name )"

                    + " VALUES ('" + artifactName + "',"
                    + "'" + originalName + "');");
            stm.executeUpdate("insert into ORIGINAL_NAME (artifact_signature ,"
                    + "original_name )"

                    + " VALUES ('" + artifactName + "',"
                    + "'" + originalName + "');");

            

        } catch (SQLException e) {
            System.out.println("ERRO: " + e.getMessage());
        }
    }

    @Override
    public String getOriginalName(String artifactSignature) {
        String originalName = null;
        try {
            Statement stm = connection.createStatement();
            ResultSet rs = null;
            rs = stm.executeQuery("select * from ORIGINAL_NAME where artifact_signature='" + artifactSignature+ "';");
            
            while(rs.next()){
                originalName = rs.getString("original_name");
            }
            
            //stm.execute("SHUTDOWN");
        } catch (Exception e) {
            System.out.println("ERRO: " + e.getMessage());
        }
        
        return originalName;
    }

    @Override
    public List<String> getArtifactsAlternativesNames(String originalName) {
        List<String> list = new LinkedList();
        try {
            Statement stm = connection.createStatement();
            ResultSet rs = null;
            rs = stm.executeQuery("select * from ORIGINAL_NAME where original_name='" + originalName+ "';");
            
            while(rs.next()){
                list.add(rs.getString("artifact_signature"));
            }
            
            //stm.execute("SHUTDOWN");
        } catch (Exception e) {
            System.out.println("ERRO: " + e.getMessage());
        }
        return list;
    }

    @Override
    public void save(List<String> artifactNames) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
}
