/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.uff.ic.archd.db.dao;

import br.uff.ic.archd.javacode.JavaAbstractExternal;
import br.uff.ic.archd.javacode.JavaAttribute;
import br.uff.ic.archd.javacode.JavaClass;
import br.uff.ic.archd.javacode.JavaData;
import br.uff.ic.archd.javacode.JavaPrimitiveType;
import br.uff.ic.archd.javacode.JavaProject;
import java.io.File;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author wallace
 */
public class HsqldbJavaAttributeDao implements JavaAttributeDao {

    private Connection connection;

    HsqldbJavaAttributeDao() {
        try {
            File file = new File(Constants.DB_DIR);
            if (!file.exists()) {
                file.mkdirs();

            }
            Class.forName("org.hsqldb.jdbcDriver");
            connection = DriverManager.getConnection("jdbc:hsqldb:file:" + Constants.DB_DIR, "archd", "123");
            DatabaseMetaData dbData = connection.getMetaData();
            ResultSet tables = dbData.getTables(null, null, "JAVA_ATTRIBUTES", null);
            //System.out.println("NEXT "+tables.next());
            if (!tables.next()) {


                System.out.println("NAO POSSUI TABELA JAVA_ATTRIBUTES");
                Statement stm = connection.createStatement();

                stm.executeUpdate("create table JAVA_ATTRIBUTES (id bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), "
                        + "class_id bigint,"
                        + "is_final boolean,"
                        + "is_static boolean,"
                        + "is_volatile boolean,"
                        + "is_private boolean,"
                        + "is_public boolean,"
                        + "is_protected boolean,"
                        + "java_data_type varchar(1000),"
                        + "name varchar(1000),"
                        + "PRIMARY KEY (id),"
                        + "FOREIGN KEY (class_id) REFERENCES JAVA_CLASSES(id));");
            } else {
                System.out.println("TABELA JAH EXISTE JAVA_ATTRIBUTES");
            }

            //stm.execute("SHUTDOWN");

        } catch (ClassNotFoundException e) {
            System.out.println("Erro ao carregar o driver JDBC. ");
        } catch (SQLException e) {
            System.out.println("Erro de SQL: " + e);
            //e.printStackTrace();
        } catch (Exception e) {
            System.out.println("ERRO " + e.getMessage());
        }
    }

    @Override
    public void save(JavaAttribute javaAttribute, long javaClassId) {
        try {
            Statement stm = connection.createStatement();
            System.out.println("insert into JAVA_ATTRIBUTES (class_id ,"
                    + "is_final ,"
                    + "is_static ,"
                    + "is_volatile ,"
                    + "is_private ,"
                    + "is_public ,"
                    + "is_protected ,"
                    + "java_data_type ,"
                    + "name ) "
                    + " VALUES (" + javaClassId + ","
                    + javaAttribute.isFinal() + ","
                    + javaAttribute.isStatic() + ","
                    + javaAttribute.isVolatile() + ","
                    + javaAttribute.isPrivate() + ","
                    + javaAttribute.isPublic() + ","
                    + javaAttribute.isProtected() + ",'"
                    + javaAttribute.getType().getFullQualifiedName() + "','"
                    + javaAttribute.getName() + "'"
                    + ");");
            stm.executeUpdate("insert into JAVA_ATTRIBUTES (class_id ,"
                    + "is_final ,"
                    + "is_static ,"
                    + "is_volatile ,"
                    + "is_private ,"
                    + "is_public ,"
                    + "is_protected ,"
                    + "java_data_type ,"
                    + "name ) "
                    + " VALUES (" + javaClassId + ","
                    + javaAttribute.isFinal() + ","
                    + javaAttribute.isStatic() + ","
                    + javaAttribute.isVolatile() + ","
                    + javaAttribute.isPrivate() + ","
                    + javaAttribute.isPublic() + ","
                    + javaAttribute.isProtected() + ",'"
                    + javaAttribute.getType().getFullQualifiedName() + "','"
                    + javaAttribute.getName() + "'"
                    + ");");
        } catch (SQLException e) {
            System.out.println("ERRO: " + e.getMessage());
        }
    }

    @Override
    public void getJavaAttributesFromClass(JavaClass javaClass, JavaProject javaProject) {
        try {
            Statement stm = connection.createStatement();
            
            //long t1 = System.currentTimeMillis();
            ResultSet rs = stm.executeQuery("select * from JAVA_ATTRIBUTES where class_id=" + javaClass.getId() + ";");
            //long t2 = System.currentTimeMillis();
            //System.out.println("Pegar todas os atributos de uma classe de uma revisão (somente o select) : "+(t2-t1)+"  milisegundos");
            
            int i = 0;
            while (rs.next()) {
                JavaData javaData = javaProject.getClassByName(rs.getString("java_data_type"));
                if (javaData == null) {
                    if (JavaPrimitiveType.getType(rs.getString("java_data_type")) != 0) {
                        javaData = new JavaPrimitiveType(JavaPrimitiveType.getType(rs.getString("java_data_type")));
                    } else {
                        javaData = javaProject.getJavaExternalClassByName(rs.getString("java_data_type"));
                        if (javaData == null) {
                            javaData = new JavaAbstractExternal(rs.getString("java_data_type"));
                            javaProject.addExternalClass((JavaAbstractExternal) javaData);
                        }
                    }
                }
                JavaAttribute javaAttribute = new JavaAttribute(javaData, rs.getString("name"),
                        Boolean.valueOf(rs.getString("is_final")),
                        Boolean.valueOf(rs.getString("is_static")), Boolean.valueOf(rs.getString("is_volatile")),
                        Boolean.valueOf(rs.getString("is_private")),
                        Boolean.valueOf(rs.getString("is_public")), Boolean.valueOf(rs.getString("is_protected")));

                javaClass.addAttribute(javaAttribute);
                i++;
            }
            //stm.execute("SHUTDOWN");
            //System.out.println("QUANTIDADE: " + i);
        } catch (Exception e) {
            System.out.println("ERRO attribute: " + e.getMessage());
        }
    }
}
